const routeDescriptions = {

route1: [
"DTC",
"Troy Road",
"Station Road",
"St Margarets Road",
"St Margarets Avenue",
"Stanhope Avenue",
"Long Row",
"Brownberrie Avenue",
"Brownberrie Drive",
"Brownberrie Lane",
"West End Lane",
"West End Rise",
"Hall Lane",
"Rawdon Road",
"New Road Side",
"Abbey Road",
"Abbeydale Way",
"Woodhall Drive",
"Vesper Road",
"Cragside Walk",
"Lea Farm Road",
"Butcher Hill",
"Low Lane"
],

route2: [
"DTC",
"Low Lane",
"Butcher Hill",
"Old Farm Approach",
"Latchmere Drive",
"Latchmere Cross",
"Fillingfir Drive",
"Ring Road",
"Broadway",
"New Road Side",
"Victoria Drive",
"Victoria Crescent",
"Victoria Gardens",
"Newlaithes Road",
"Newlay Lane",
"Abbey Road",
"Abbey Walk",
"Spen Lane",
"Ghyll Road",
"Queenswood Drive"
],

route3: [
"DTC",
"Low Lane",
"Butcher Hill",
"Lea Farm Road",
"Cragside Walk",
"Hawksworth Avenue",
"Hawksworth Crescent",
"Lea Farm Drive",
"Lea Farm Road",
"Vesper Road",
"Spen Lane",
"Old Farm Approach",
"Latchmere Drive",
"Ring Road",
"Rawdon Road",
"Layton Lane",
"Layton Road",
"Brownberrie Lane",
"Station Road",
"Troy Road"
]

};
